---
- name: setup pre-requisites
  hosts: all
  become: yes
  roles:
    - create-sudo-user
    - install-modules
    - configure-hosts-file

- name: setup docker user on the nodes
  become: yes
  become_user: docker
  hosts: admin
  roles:
    - configure-admin

- name: copy public key to nodes
  become: yes
  become_method: sudo
  become_user: root
  hosts: docker-nodes
  roles:
    - copy-keys

- name: install docker
  hosts: docker-nodes
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - docker-installation

- name: initialize docker swarm
  hosts: swarm-manager
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - docker-swarm-init

- name: add workers to the swarm
  hosts: swarm-workers
  become: yes
  become_method: sudo
  become_user: root
  roles:
    - docker-swarm-add-worker

- name: Install docker-registry
  hosts: swarm-manager
  become: yes
  become_method: sudo
  become_user: root

  vars_files:
    - roles/docker_registry/defaults/main.yml
    - roles/docker_registry/vars/main.yml

  tasks:
    - include: roles/docker_registry/tasks/main.yml

  handlers:
    - include: roles/docker_registry/handlers/main.yml