---

 - name: check docker sdk version
   shell: pip install docker
   ignore_errors: true

 - name: Creating a docker service of internal registry
   docker_swarm_service:
          name: "{{ registry_name }}"
          image: registry:2
          publish:
            - published_port: "{{ registry_port }}"
              target_port: 5000
          mounts:
            - type: volume
              target: "{{ registry_volume_path }}"
              source: "{{ registry_volume_source }}"
   vars:
      ansible_python_interpreter: /usr/bin/python

 - name: Sleep for 20 seconds so docker registry service will start
   wait_for:
      timeout: 20

 - name: checking if the registry is working or not
   shell: curl http://172.16.233.60:{{registry_port}}/v2/
   register: status

 - name: checking the status of registry
   debug:
     msg: "{{ status.stdout_lines }}"
